### ISSUE TITLE
User is not able to select the source / Destination field in set location on map screen (Parent_Id-#1594)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1604]
#1594 
[User is not able to select the source / Destination field in set location on map screen](https://drive.google.com/file/d/153Y6KAxC0a5Lt_wLS2OFEkLr0_wsqtEz/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials
2. Tap on "where to" and tap "select location on map" 
3. In select location on map screen, clear the location in "source field" 
4. The field highlighter will move to source field
5. Tap on destination field

**Expected Result**
         The highlighter should be moved to destination field and user should be able to select the location using map pointer

**Actual Result**
          User is not able to move to the destination field and same issue is there for source field as well

**Comment by tejkranthi** [comment]
Non-critical

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
@mohdshoaib18169 [reopening the issue. It seems not to be fixed](https://drive.google.com/file/d/182J-yq4JgwgomrIEwIo-2zwvDQcPN5Ch/view?usp=sharing)

**Comment by rohanrp179** [comment]
@mohdshoaib18169 Can u comment here. it looks like not fixed...

**Comment by mohdshoaib18169** [comment]
@rohanrp179 , its there in Namma Yatri production also,
currently we can't fix (its due to the same issue that happens in cursor visibility while selecting gender because it only happens when you click close button the focus doesn't change)

**Comment by rohanrp179** [comment]
@tejkranthi Closing this issue as this is still in prod
