### ISSUE TITLE
Update button is enable even though name field is blank (Parent_Id-#1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1616]
#1594 

**Description** 
[Update button is enable even though name field is blank](https://drive.google.com/file/d/13y3SYnn6W60vLmaz15_b2kMn4dTlgvT2/view?usp=sharing)

**Steps to reproduce**
1.Lanuch the application
2.login with valid credentials 
3.Click on hamburger-->Click on profile-->Click on edit button
4.Remove name-->Enter valid email-id-->Update gender button
5.Observe the update button

**Expected Result**
Update button should be disabled if name field is blank

**Actual Result**
Update button is enable even though name field is blank

**Comment by MercyQueen** [comment]
Fixed

**Comment by krupal-14** [comment]
This issue is fixed

**Comment by rohanrp179** [comment]
@MercyQueen 

[reopening the issue . it is still persisting. When ride is assigned and user is on ride OTP screen, that time if user keeps name blank , user can click on update button.

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
Closing the issue as retesting is successfully
