### ISSUE TITLE
Some times app is not launching(Parent_Id-1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1692]
#1594 
**Description**
[Some times app is not launching](https://drive.google.com/file/d/1-2z7DUpCoR5WtghugMMvjLdNfvUyU7OT/view?usp=sharing)

Start watching from 1min

**Steps to Reproduce**
1.Launch the apk
2.Initiate the ride.
3.No driver accepts the ride.
4.Try again pop-up is displayed.
5.Kill the user apk and relaunch.

**Expected Result**
App should Launch

**Actual Result**
App freezes

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
@tejkranthi @mohdshoaib18169 
[The issue is not fixed. Still present](https://drive.google.com/file/d/18_EVciopXqzjO8H2EqYZI_RIyLh0R6xb/view?usp=sharing)

**Comment by mohdshoaib18169** [comment]
@rohanrp179 , it will only happen in master , not in production ,
you can clear it with @tejkranthi

**Comment by rohanrp179** [comment]
Sure. Closing the issue @tejkranthi
