### ISSUE TITLE
The link is not being shared via share app (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1820]
#1803 

[The link is not being shared via share app. Sent from text message, slack and whatsapp. Everywhere link is not being sent](https://drive.google.com/file/d/12Q2NHoF5kEou9O2vAK7NIDYuyPUe272-/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Click on Share app

**Expected result**
Through the message link should go

**Actual result**
The link is not going

**Comment by MercyQueen** [comment]
Fixed.

**Comment by johnruban-4050** [comment]
@MercyQueen Issue still exist , Can you please check

https://github.com/nammayatri/nammayatri/assets/137036742/9c8c7d5e-b2d9-4319-9b60-d49e7f83e2b0

**Comment by MercyQueen** [comment]
Fixed.

**Comment by johnruban-4050** [comment]
Retested and its working fine as expected
