### ISSUE TITLE
Driver is getting ride request even though date and time is inaccurate(Parent_Id-1902)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1904]
#1902 
**Description**
[Driver is getting ride request even though date and time is inaccurate](https://drive.google.com/file/d/1OmXjlFsTUcGSNNXKPfPiBvZWOf3liCwP/view?usp=sharing)

Steps to reproduce
1.Launch the driver application.
2.Login with valid credentials.
3Change the date and time.
4.Wait for 3 min. 
5.Observe the screen.

Expected Result
Driver should not get any ride request

Actual Result
Driver is getting ride request.

**Comment by guptamanav422** [comment]
Fixed

**Comment by krupal-14** [comment]
@ManavGuptaJuspay Driver is still getting ride request even though driver time is wrong

**Comment by guptamanav422** [comment]
FIXED
