### ISSUE TITLE
User chat are displayed twice on Chat screen (Parent_ID-#1867)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1927]
#1867
[User chat are displayed twice on chat screen](https://drive.google.com/file/d/1kgMCrfFM12EzGxnC9Z7PVGhROtO4fesI/view?usp=sharing)

Step to reproduced:-
1. Launch the app
2.  Book the ride
3. verify the Chat box 
4.  observe the issue

Expected result : -
Chat should display at only one time

Actual result: -
Chat are displayed  twice

Reproduce rate - 3/5

Device - iPhone XR (16)

**Comment by johnruban-4050** [comment]
Retested and working fine as expected

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
@MercyQueen Retested.This issue is working fine but After launching the app after a min previous messages are disappearing and message focusing issues are still exist the possibility of that bug is 1/8.
