### ISSUE TITLE
In try again screen car icon is missing(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1947]
#1867 
[In try again screen car icon is missing](https://drive.google.com/file/d/13UQG7nLZosYBQeAh4_IrhkmOI9tULidg/view?usp=sharing)

**Steps to reproduce**
1. Search for a ride
2. Wait for try again screen and observe 

**Expected Result**
In try again screen car icon should come

**Actual Result**
In try again screen car icon is missing

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Not fixed,Reopen

![Image](https://github.com/nammayatri/nammayatri/assets/132905061/4a098f82-ad46-40f9-a43e-b9a59c9fa497)

**Comment by MercyQueen** [comment]
It should be fixed now.

**Comment by rohanrp179** [comment]
Working as expected . Closing now
