### ISSUE TITLE
Rate Card - Driver Additional  fee is displayed wrong(Parent_id-#2164)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2180]
#2164 
[Rate Card - Driver Additional  fee is displayed wrong](https://drive.google.com/file/d/1wzQYNSSxa7JZn8wlyLP27tC6P8_LcA3H/view?usp=sharing)
 Step to reproduce:-
1. launch the app
2. Search the ride
3. Get Estimation
4. Click on info icon of auto 
5. Observe the issue

Expected result:-
Driver additional fee should display correctly

Actual result:-
Driver additional fee displayed wrong

Reproduce rate - 5/5
Device - Oppo F7

https://drive.google.com/file/d/1ciTZ2wZpGOurSJzfmpE9PW_WbsTs4MaT/view?usp=sharing

**Comment by johnruban-4050** [comment]
Driver Addition Fee should display as ₹10 for Auto rickshaw & ₹20 for other variants

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Rajaprabhu-Natrajan** [comment]
Issue still exist. Kindly refer screenshot 

![Image](https://github.com/nammayatri/nammayatri/assets/134508712/b50a9a32-1ef4-4e70-a202-73288c8f4b16)

**Comment by prakharritik** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Fixed
