### ISSUE TITLE
The start and end time is missing in invoice downloaded from Ride details from Rate your driver screen (Parent_Id - 1867)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2246]
#1867 

The start and end time is missing in invoice downloaded from Ride details from Rate your driver screen

**Steps**
1. Log in to app
2. Book a ride and end it
3. Click on Ride details on Rate your driver screen

**Expected result**
The invoice should have time also when ride started and ended

**Actual result**
The time of when ride started and ended is missing
[Yatri_Ride_Fri, 4th Aug_.pdf](https://github.com/nammayatri/nammayatri/files/12261255/Yatri_Ride_Fri.4th.Aug_.pdf)

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
@MercyQueen This issue is still there. If we kill and reopen the app then it is coming properly.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
Working as expected. Closing it
