### ISSUE TITLE
The page contents is not translated in profile screen when the language is changed to hindi and bengali(Parent_Id - #2096)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#2374]
#2096 
[The page contents is not translated in profile screen when the language is changed to hindi and bengali](https://drive.google.com/file/d/1ICRfKGsk3yIzAfH-eXveCNRDqAjYVzqx/view?usp=sharing)

**Steps to reproduce**
1. Launch the apk and login with valid credentials 
2. Go to profile screen > settings
3. Go to language and select bengali or hindi 
4. Come back to driver details page ,verify  under summary section 
5. Go to vehicle details screen and observe the screen 

**Expected result**
All the contents in the profile screen should be translated to the selected language 

**Actual result**
The content under the summary section and the texts in the vehicle details screen is not translated to bengali / hindi.

**Comment by johnruban-4050** [comment]
issue Still exist

**Comment by Sumedh-14** [comment]
Retested on 17/08, "x months on YS"text in chip carousel is not translated

PFA below, 
https://drive.google.com/file/d/1wM05_ax3DjrGl_p3gP8KVxQ9UgQ6s2he/view?usp=sharing

**Comment by aryanguptaSG** [comment]
config . @ashishsingh101

**Comment by Akash2172** [comment]
Fixed

**Comment by rohanrp179** [comment]
X months on is still not fixed. @Akash2172 It is still shown in English for if driver choose other language

**Comment by rohanrp179** [comment]
@ashishsingh101

**Comment by rohanrp179** [comment]
closing this as no response in this
