### ISSUE TITLE
Not able to save any location as favourites in a certain flow (Parent_Id- #1803)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#2593]
#1803 
[Not able to save any location as favourites in a certain flow ](https://drive.google.com/file/d/19VK6tohUBsv3N_AfAlvKALo_Z7M8Cx7-/view?usp=sharing)

**Steps to reproduce**
1. Launch the apk and login with valid credentials
2. Tap on hamburger menu and go to favourites
3. Tap on "Add favourites" select any location and save that location with home or work tag 
4. Again try to add a location in favourites then "In add favourite" location page, tap on "favourite" tag 
5. Enter "home" or "work" as a tag name which is saved before.
6. An error message will display "name already exists" 
7. Select "home" or "work" tag which is unsaved and observe the "confirm & save" button

**Expected Result**
"Confirm & Save" button should be enabled when trying to save a location as favourites with unsaved tag name 

**Actual Result**
"Confirm & Save" button is greyed out.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retesed,issue is still exist
https://drive.google.com/file/d/1IW6aF8C1xVea5GfDILN1TKR4QXXqfX29/view?usp=sharing

**Comment by MercyQueen** [comment]
fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
