### ISSUE TITLE
16/10/23_NYU_Ridesearch_The entered text is not cleared in "Destination" field when user goes to "Set location on map" screen (Parent_Id - 1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3682]
#1980 
[The entered text is not cleared in "Destination" field when user goes to "Set location on map" screen](https://drive.google.com/file/d/15wYKfCNBovmVd8mfrUgUTe2ChkUYZvXt/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with valid credentials
2. Tap on "where to?" and enter some text then suggestions will display
3. Tap on "Set location on map" 

**Expected result**
The entered text  should not display in "where to"

**Actual result**
The entered text is displaying in "where to" in "set location on map" screen.

**Comment by aryan-13** [comment]
@ashkritidewan2000 Can you update this

**Comment by ashkriti** [comment]
Sure, this is an issue in prod currently. Will fix this

**Comment by ashkriti** [comment]
Fixed

**Comment by Rajaprabhu-Natrajan** [comment]
Still issue persists on this apk (20/10/2023)
video reference -  https://drive.google.com/file/d/1VOmNkgk7HMGmGc4FgJ6tdByOUb8ca73k/view?usp=sharing

**Comment by AlluGowthami28** [comment]
@ashkriti @aryan-13 Still issue persists in this apk
https://drive.google.com/file/d/1VEBSwTNsuJsS2Xyba9exF01Ml_2FYlin/view?usp=sharing
