### ISSUE TITLE
16/10/23_NY_Android_Try Again Screen_Car icon is coming in try again screen_Parent_Id - 1980) 

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#3737]
#1980

Car icon is coming in try again screen

**Step to reproduce** 
1. Search for a ride 
2. Wait until timer gets completed

**Actual result**
Car icon is coming in try again screen

**Expected Result**
Auto icon should come in try again screen

![Screenshot_20231016-180430_Namma Yatri](https://github.com/nammayatri/nammayatri/assets/139038923/a565d0e8-7c77-40e2-ba22-48a94c0a9dea)

**Comment by aryan-13** [comment]
@Anuragini-2506 Can you check and update this issue

**Comment by Anuragini-2506** [comment]
@prakharritik can you look into this ? This bug was introduced in the PR for enabling the Tips

**Comment by Anuragini-2506** [comment]
fixed

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine

**Comment by AlluGowthami28** [comment]
@Rajaprabhu-Natrajan @Anuragini-2506 issue still there in latest apk.

**Comment by AlluGowthami28** [comment]
@Anuragini-2506 issue still there in latest apk.
![20231027_165232](https://github.com/nammayatri/nammayatri/assets/139038923/dd4ba6a5-d23b-459e-a894-a701c1c0a1cb)
