### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding>Text is in english even though driver chooses kannada/Hindi/Tamil as lanaguge.<parent_id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4223]
#1980 
[Text is in english even though driver chooses kannada/Hindi/Tamil as lanaguge](https://drive.google.com/file/d/1zVRSOVqlDeIhvlLDDhAp2N5sjcuupeNX/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give location permission.
3.Select valid city & language(Kannada/Hindi/Tamil)
4.Click on confirm & click on get started.
5.Observe  the enter mobile number screen

Expected Result
ಮುಂದುವರಿಸು ಕ್ಲಿಕ್ ಮಾಡುವ ಮೂಲಕ ನೀವು ನಮ್ಮT&C's ಸಮ್ಮತಿಸುತ್ತೀರಿ

Actual result
Text is in default langauge not in driver selected language.

**Comment by Rohit4997** [comment]
Fixed

**Comment by krupal-14** [comment]
Issues Still exist .
https://drive.google.com/file/d/1JO6HzG54m6Y9sgRkfhRw2h5KH2idiD4U/view?usp=sharing

**Comment by Gowthami1309** [comment]
Fixed.
