### ISSUE TITLE
8/11/23><NYP> <Android><Onboarding> Logout option should be present in kannada when driver language is in kannada <parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4231]
#1980
Logout option should be present in kannada when driver language is in kannada 

Steps:

- Open application
- Change language in kannada
- Be in mobile number screen
- Enter driver mobile number
- click on continue
- Enter OTP
- Verify logout in 

Expected: Logout should be in kannada as "ಲಾಗ್ ಔಟ್"

![Screenshot_20231108_124339_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/af620fe9-0488-4b46-869d-12bdcd88823d)

**Comment by ashkriti** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Not fixed, hence reopening this issue.


![Image](https://github.com/nammayatri/nammayatri/assets/131981246/969703c4-fadb-4938-8151-1c9fb1b5d532)

**Comment by Gowthami1309** [comment]
issue resolved.
