### ISSUE TITLE
6/12/23_Y_UIREVAMP_ UI Issues _ Parent_id_1594

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4617]
#1594 
**UI ISSUES**

1. Welcome to namma yatri is showing in home screen ([Here](https://juspay.slack.com/files/U048PG24YQP/F068ETZAKST/tempfileforshare_20231206-140811.jpg))
2. Bengaluru's most loved auto app is showing in kochi app ([Here](https://juspay.slack.com/files/U048PG24YQP/F069J7XBZL0/tempfileforshare_20231206-140741.jpg))
3.

**Comment by aryan-13** [comment]
1,2 are fixed.
3 is not reproducible.

**Comment by MercyQueen** [comment]
4 -> Fixed.

**Comment by Gowthami1309** [comment]
Issue 3 still existing 


![Image](https://github.com/nammayatri/nammayatri/assets/150240985/8c65e100-6b05-4be6-88f9-02d8a4cb90fe)

**Comment by Vinaykm999** [comment]
Issue 3 retest, working fine.
![Screenshot_2023-12-12-17-41-38-82_0ed48e1b8b56d746f8e789ae9a4c0a46](https://github.com/nammayatri/nammayatri/assets/131981246/097d76a1-ada1-4b8b-9e01-15b4116622d1)
