### ISSUE TITLE
29/04/24_NY_Android_BookAny_ Book any option is expanded even user completed a ride & try to book one more ride. _(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6604]
#1980
 Book any option is expanded even user completed a ride & try to book one more ride.[[Here](https://drive.google.com/file/d/1ISdIZsbhjyX6DxcoAEM8OSPX28nWiPNY/view?usp=sharing)]
 
 Steps To reproduce.
 1.Launch the user apk.
2.Login with valid credentials.
3. Try to book a ride-->Observe the book any option.
4. Click back button navigate to home screen try to book one more ride & observe the book any option in estimate screen.

Expected result
Book any option should not expanded till user clicks on that.

Actual result
Book any option is expanded all the time with user is clicking.

**Comment by PraveenGongada** [comment]
Fixed

**Comment by Vinaykm999** [comment]
@PraveenGongada 
This issue is still exist, hence reopening this. - [PFA](https://drive.google.com/file/d/1ecSkwC7vss49X0vpGUbus5VtPo3G3Qut/view?usp=sharing)

**Comment by Vinaykm999** [comment]
As per dev comment it is expected. Hence we are resolving this.
