### ISSUE TITLE
11/06/24_<NYP><Android><Master> <Driver vehicle rate>Youtube video is coming for all the cities (Parent id_1980)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#7218]
#1980 

**Describe the bug**
Learn More --> Youtube video is coming for all the cities, As per figma, it should be for only BLR, Mys & Tumakuru. 

**To Reproduce**
-Move the driver location to Other city like Chennai. 
-Validate the Home Screen.
-Tap on Booking Preferences. 
-Validate the Namma Yatri Card
- Tap on Namma Yatri rate Card
- Validate the Learn More --> YouTube Video 

**Expected behavior**

**Screenshots**

**App (please complete the following information):**

**Additional context**

**Comment by Rohit4997** [comment]
Fixed

**Comment by 123ajay1994** [comment]
This issue is not fixed, still able to see you tube for Hyd city. 
So marking it open. 
https://drive.google.com/file/d/1ZsdaZYwqQ2cgciatbNVTxUXouEAuH4Y0/view?usp=sharing

**Comment by witcher-shailesh** [comment]
@Rohit4997

**Comment by Rohit4997** [comment]
@witcher-shailesh  It is already fixed.
@123ajay1994  You cannot changes driver's city by just changing the location, You have to either uninstall/reinstall or change it from dashboard

**Comment by 123ajay1994** [comment]
@Rohit4997 yes, Acknowledged &&  Re checked and it is not coming. 
marking this as Done. 
https://drive.google.com/file/d/1UQYGv_yoVu6UuxiTAsEG4MT1OCmLULea/view?usp=sharing
